export const input: string;
export const text: string;
export const select: string;
export const label: string;
export const withIcon: string;
export const icon: string;
export const noMargin: string;
export const radio: string;
export const checkbox: string;
